NEGATIVE_DIRECTION = {
    "JOB_LOSS_RISK",
    "SERVICE_OBSTRUCTION",
    "VALUE_DESTRUCTION",
    "TERMINATION",
    "RESIGNATION"
}

POSITIVE_DIRECTION = {
    "CAREER_RISE",
    "STATUS_AND_RECOGNITION",
    "GAIN",
    "INCOME_GAIN"
}